use std::{
    fmt,
    fmt::{Debug, Display, Formatter},
};

/// The Basic DataPoint struct containing the state of the simulation on a particular degree day
#[derive(Debug)]
pub struct DataPoint<const NUM_GEN: usize> {
    pub pop_captured: f64,
    pub pop_active: [f64; NUM_GEN],
    pub eggs: [f64; NUM_GEN],
    pub eggs_total: [f64; NUM_GEN],
}

// Allow for DataPoint's to be turned into a row of comma seperated values
impl<const NUM_GEN: usize> Display for DataPoint<NUM_GEN> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let pop_active_string: String = self
            .pop_active
            .clone()
            .into_iter()
            .fold("".to_owned(), |acc, x| format!("{}{},", acc, x));

        let eggs_string: String = self
            .eggs
            .clone()
            .into_iter()
            .fold("".to_owned(), |acc, x| format!("{}{},", acc, x));

        let eggs_total_string: String = self
            .eggs_total
            .clone()
            .into_iter()
            .fold("".to_owned(), |acc, x| format!("{}{},", acc, x));

        write!(
            f,
            "{},{}{}{}",
            self.pop_captured, pop_active_string, eggs_string, eggs_total_string
        )
    }
}
impl<const NUM_GEN: usize> DataPoint<NUM_GEN> {
    /// Does as the name suggests. It is necessary to get headers for a concrete instance of DataPoint because the size of the arrays it contains changes based on the number of generations simulated.
    pub fn csv_headers(&self) -> String {
        let pop_headers = self
            .pop_active
            .clone()
            .into_iter()
            .enumerate()
            .fold("".to_owned(), |acc, (i, _)| {
                format!("{acc}pop_active_{},", i)
            });

        let egg_headers = self
            .eggs
            .clone()
            .into_iter()
            .enumerate()
            .fold("".to_owned(), |acc, (i, _)| format!("{acc}eggs_{},", i));

        let egg_total_headers = self
            .eggs_total
            .clone()
            .into_iter()
            .enumerate()
            .fold("".to_owned(), |acc, (i, _)| {
                format!("{acc}eggs_total_{},", i)
            });

        format!("dd,captured,{pop_headers}{egg_headers}{egg_total_headers}")
    }
}

/// Newtype for a Vector of DataPoints so that new methods can be implemented on it.
pub struct DataPointFrame<const NUM_GEN: usize>(pub Vec<DataPoint<NUM_GEN>>);

impl<const NUM_GEN: usize> DataPointFrame<NUM_GEN> {
    /// Creates an entire csv file for a single data set generated by the simulation.
    pub fn to_csv_string(&self) -> String {
        let headers = self.0.get(1).unwrap().csv_headers();
        let data = self
            .0
            .iter()
            .enumerate()
            .map(|(idx, x)| format!("{},{}\n", idx, x.to_string()))
            .collect::<Vec<String>>()
            .join("");
        format!("{}\n{}", headers, data)
    }
}
